### ISSUE TITLE
Rename this software.

### ISSUE THREAD

**Issue by JoshS** [godotengine/collada-exporter#104]
The name "Better Collada" implies that the GNU/Blender is the reason that Godot can't import the file properly. It's a blatant lie.  The Collada exporter workers fine on multiple other engines and literally only Godot has an issue with it.

Rename "Better Collada" to "Collada Workaround for Godot" or something similar.  It's not GNU/Blenders fault that Godot importing is buggy and primitive and the implication that it is GNU/Blenders fault is absolutely ridiculous and misleading.

Regards,
Josh Spenzf

**Comment by Calinou** [comment]
I don't think there's "Better Collada" implies that the built-in exporter is broken. Compare it to "Better Grass" in Minecraft: it doesn't imply the apperance of the default grass is *broken*, it just claims to make it *better* (which is completely subjective).

**Comment by akien-mga** [comment]
Since when is Blender a GNU project?

**Comment by JoshS** [comment]
> Since when is Blender a GNU project? If we want to bikeshed on software naming, let's not be misleading.

It uses the GNU corelibs so it is GNU software, whether they like it or not.
Give GNU the proper respect and say GNU/Blender.

**Comment by hpvb** [comment]
This person has trolled with issues before.
