### ISSUE TITLE
Test model comes pretty broken when importing on godot.

### ISSUE THREAD

**Issue by ca3games** [godotengine/collada-exporter#106]
Test with animated model comes really broken, not sure what's the reason.

![Captura de pantalla de 2019-05-09 16-45-24](https://user-images.githubusercontent.com/19626687/57488912-17a86800-727a-11e9-974e-0af78dc8ac49.png)

Feel free to use my free azuka blender model for testing purposes:
https://github.com/ca3games/ART/tree/master/Evangelion/azuka
(azuka.blend file)

**Comment by volzhs** [comment]
![Screenshot_20190510_073043](https://user-images.githubusercontent.com/8281454/57490838-8d9de500-72f5-11e9-8f64-d538a8b91179.png)

need to export with T-pose

**Comment by ca3games** [comment]
> ![Screenshot_20190510_073043](https://user-images.githubusercontent.com/8281454/57490838-8d9de500-72f5-11e9-8f64-d538a8b91179.png)
> 
> need to export with T-pose

Do I need an initial animation with a T-pose?

**Comment by volzhs** [comment]
I mean all bones are need to be reset before exporting.
mesh should not be deformed by bones when exporting.

**Comment by ca3games** [comment]
> I mean all bones are need to be reset before exporting.
> mesh should not be deformed by bones when exporting.

Ah, ok, let me test.
It would be nice if that was a warning on the docs.

**Comment by ca3games** [comment]
Yes, got it working, thanks.

**Comment by volzhs** [comment]
cc @godotengine/documentation
