### ISSUE TITLE
Add-on requires 2.8x but already on 2.82

### ISSUE THREAD

**Issue by Senre** [godotengine/collada-exporter#118]
I followed the instructions on where to put the files into the add-ons folder but blender complains that it needs to be on 2.8x when the version I'm using is 2.82.

![pic](https://user-images.githubusercontent.com/44935191/75344157-f2521c80-58d4-11ea-9219-963757480efb.png)

For that reason, I cannot export to BetterCollada

**Comment by Calinou** [comment]
The add-on in the `master` branch is only compatible with Blender 2.79. Try using this fork: https://github.com/HungryProton/collada-exporter-2.8
