### ISSUE TITLE
using Blender 2.82 but better collada says need to upgrade to 2.8x

### ISSUE THREAD

**Issue by wahyuadiramadan** [godotengine/collada-exporter#119]
error after nstalling better collada addon, the error says need to upgrade to 2.8x meanwhile im using 2.82 when installing it.

**Comment by andersmmg** [comment]
This is saying the addon needs to be updated not Blender. This addon isn't made for 2.8x

**Comment by wahyuadiramadan** [comment]
Oo i see thats why it still work in older blender thsnk you🙏🙏

**Comment by Calinou** [comment]
Closing, as the main repository containing this add-on hasn't been updated for Blender 2.8 yet. In the meantime, consider using glTF 2.0 or the [Godot Blender Exporter](https://github.com/godotengine/godot-blender-exporter) add-on.
