### ISSUE TITLE
Better Collada still listed on the godotengine.org Download page

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/collada-exporter#125]
As far as I know GLTF2 is now the recommended way to export from Blender. Following the Community channels, I get the impression there seem to be less issues with GLTF2.

Having Better Collada listed so prominently, makes is seem like the recommended way to export from Blender. More so, if I don't know what "Collada" means (maybe because I'm new to Blender or 3D modelling all together), my mind reads "An improved exporter for Blender". Why would I not use that? I would definitely try this Collada thing before GLTF2. If I read about GLTF2 being recommended, I would get confused. "I thought Collada was the improved one?", "Why do they then have the Collada on the official download page saying this is the improved method to export from Blender?"

Unless I'm mistaken on GLTF2 being the recommended way to export now, I would suggest to remove that Collada download link all together.
https://godotengine.org/download

**Comment by gau-veldt** [comment]
I believe current work is now towards GLTF2 and the direct-to-Godot-scene (.scn) exporter.  The Godot manual is known to be out of date in some places.
________________________________

**Comment by volzhs** [comment]
as my testing for better collada with 2.79 / godot exporter(.escn) and gltf2 with 2.8, shapekey animation only works with better collada.
I think gltf2 needs some more work before removing better collada from download page.

**Comment by Calinou** [comment]
I think the bigger issue right now is that the upstream version of Better Collada doesn't support Blender 2.80 and later.

Did the built-in Collada exporter improve significantly in Blender 2.80 onwards?

**Comment by tinmanjuggernaut** [comment]
Better Collada is the only exporter I know of that will extract a mesh with multiple animations from Blender 2.8x. GLTF and escn currently do only one or none. The only problem with Better Collada is it doesn't do materials. So export with BC, then export again with GLTF to get the material, or manually create it in Godot.

**Comment by golddotasksquestions** [comment]
@tinmanjuggernaut 
Apparently GLTF 2.0 export works with multiple animations if you add all of them as NLA tracks:
https://www.reddit.com/r/godot/comments/j6zizb/til_to_export_multiple_animation_to_gltf_20_from/

**Comment by smix8** [comment]
The official Godot page is not listing the "Godot Blender Exporter" for .escn files as a (better) alternative right next to the Collada Addon on the main download page. So many Godot issue reports with 3D models in the past months point to the usage of old/broken 3D (Collada) exporters. I don't know who is maintaining the Godot website but the people should be better made aware of alternative export tools that work more reliably.

**Comment by amoriqbal** [comment]
Please checkout this article too. I got the same confusion from this one. 
https://godotengine.org/article/importing-3d-assets-blender-gamedevtv

**Comment by JigmeDatse** [comment]
The article that @amoriqbal points to is what brought me to this project (collada exporter) and it doesn't work with Blender 2.8 or 2.9 (current stable).  The 2.9 builtin collada export, will export something which can be imported, as does the builtin gltf export.

Without this project being updated, (which it seems like it's been 2.5 years since a commit), that either Godot needs to provide better options.

There's also the godot-blender-exporter, which exports a .escn but it recommends using the builtin gltf2 exporter.  

This is more a matter that it ends up taking time to get to where you need to go, which is partially because the godot.org site is pointing to this project.

**Comment by Calinou** [comment]
See https://github.com/godotengine/godot-proposals/issues/2130.

**Comment by Calinou** [comment]
Fixed by https://github.com/godotengine/godot-website/pull/251.
