### ISSUE TITLE
Plug-in doesn't show up in the Add-ons list

### ISSUE THREAD

**Issue by thetalmid** [godotengine/collada-exporter#126]
I'm using Blender 2.82. Did everything according to the README. "Better Collada Exporter" and "Godot Export Manager" both missing from the list -- could it be an issue with permissions?

**Comment by s-cheadle** [comment]
@thetalmid I think it is an issue with the plugin not being supported in newer versions yet. I got it working by using the version of the plugin from [here](https://github.com/Oxel40/collada-exporter/tree/blender-2.83-support) that is mentioned in #123

**Comment by Calinou** [comment]
Duplicate of https://github.com/godotengine/collada-exporter/issues/96.
