### ISSUE TITLE
Sketchup exported collada can not be imported properly.

### ISSUE THREAD

**Issue by Frontrider** [godotengine/collada-exporter#129]
When importing dae from Sketchup, the import gets several different errors. Importing the same dae file into blender then exporting it as dae always fixes it, but is not a working solution. Sketchup does not have GLTF support so this is the only format that can work.

This dae file produces this error:
https://cdn.discordapp.com/attachments/275788728168087556/871370866452226058/terrain.dae
https://cdn.discordapp.com/attachments/275788728168087556/871370304478392330/2021-08-01_14-34-20.png
```editor/collada/collada.cpp:1060 - Primitive type "polygons" is not well supported (concave shapes may fail). To ensure that the geometry is properly imported, please re-export using "triangles" or "polylist".```
This was fixable by changing that "polylist" setting to triangles.

With tringles enabled, we get this:
https://cdn.discordapp.com/attachments/275788728168087556/871376248692154408/terrain.dae
![image](https://user-images.githubusercontent.com/6755034/127772283-a650d681-e1c2-4e82-8afc-13ed9bbc257c.png)
with this error:
``` editor/collada/collada.cpp:1691 - Multiple instance_* not supported.
 editor/collada/collada.cpp:1691 - Multiple instance_* not supported.
 editor/collada/collada.cpp:1691 - Multiple instance_* not supported.
 editor/collada/collada.cpp:1691 - Multiple instance_* not supported.
 editor/collada/collada.cpp:1691 - Multiple instance_* not supported.
 editor/collada/collada.cpp:1691 - Multiple instance_* not supported.
 editor/collada/collada.cpp:1691 - Multiple instance_* not supported.
 editor/collada/collada.cpp:1691 - Multiple instance_* not supported.
 editor/collada/collada.cpp:1691 - Multiple instance_* not supported.
 editor/collada/collada.cpp:1691 - Multiple instance_* not supported.
 editor/collada/collada.cpp:1691 - Multiple instance_* not supported.
 editor/collada/collada.cpp:1691 - Multiple instance_* not supported.```

**Comment by Frontrider** [comment]
wrong repo

**Comment by Calinou** [comment]
Superseded by https://github.com/godotengine/godot/issues/51148.
