### ISSUE TITLE
Does this works with Blender 3.0?

### ISSUE THREAD

**Issue by animanoir** [godotengine/collada-exporter#130]

**Comment by Calinou** [comment]
This add-on was never officially updated past Blender 2.79, so no: https://github.com/godotengine/collada-exporter/issues/96

**Comment by Lamoot** [comment]
We're doing upgrades for the exporter to be used for Blender to OpenMW pipeline. There's some improvements, it works in Blender 3.0, but we're also adding some OpenMW specific things. Perhaps this would work for you?

https://github.com/OpenMW/collada-exporter

**Comment by animanoir** [comment]
@Lamoot thanks my dude, gonna try it!
