### ISSUE TITLE
Can't enable plugin

### ISSUE THREAD

**Issue by aragubas** [godotengine/collada-exporter#132]
![image](https://user-images.githubusercontent.com/47148297/170428597-4c47eb10-325d-494d-8493-3269e9a2eb07.png)
this happens 

Blender version is 2.79

**Comment by Calinou** [comment]
This add-on now only supports Blender 2.80 and later. The last commit with Blender 2.79 support is https://github.com/godotengine/collada-exporter/commit/9a8fae951fe76209a7bb6c6cbc692478585283b8 ([download a ZIP](https://github.com/godotengine/collada-exporter/archive/9a8fae951fe76209a7bb6c6cbc692478585283b8.zip)).

**Comment by aragubas** [comment]
> This add-on now only supports Blender 2.80 and later. The last commit with Blender 2.79 support is [9a8fae9](https://github.com/godotengine/collada-exporter/commit/9a8fae951fe76209a7bb6c6cbc692478585283b8). [Download a ZIP of that commit](https://github.com/godotengine/collada-exporter/archive/9a8fae951fe76209a7bb6c6cbc692478585283b8.zip) and install that version of the add-on.

Thanks!
