### ISSUE TITLE
README does not provide information about godot_export_manager.py

### ISSUE THREAD

**Issue by gau-veldt** [godotengine/collada-exporter#35]
There is this script godot_export_manager.py however there is no mention of it in the README or how to use in Blender?  Is it a one-off to run in the script window, or is it to be installed somewhere?

The README only mentions to install the io_scene_dae directory, not this script.

**Comment by akien-mga** [comment]
CC @ndee85 who contributed it IINM.

**Comment by gau-veldt** [comment]
PS: I'm trying this exporter from HEAD to see if it fixes issues I've had before importing DAE into Godot.  I was tempted to write a direct Blender-to-scn (or more mordern Godot use tscn) export plugin after that experience.

**Comment by Warlaan** [comment]
I ran into some issues with the exporter simply because I didn't know that there are two Blender addons in the repo. Since I saw the Godot Export Manager first I activated it and got an error when trying to export since it depends on the other one.
So I agree, this should definitely be mentioned in the readme.

**Comment by akien-mga** [comment]
PRs welcome, I never used any of those addons so a fix would be more relevant when coming from someone who knows how to use this stuff.

**Comment by paper-pauper** [comment]
Perhaps it's better (and less confusing) to distribute them in two separate repos - they are two different addons after all, and one depends on the other.

**Comment by Warlaan** [comment]
The main issue is that Blender doesn't have a mechanism for dependencies between addons, or does it?
But strictly speaking you are correct, it would be the cleanest solution if they were two separate repos with one referencing the other as a submodule.

**Comment by Warlaan** [comment]
I created this pull request to fix the readme: https://github.com/godotengine/collada-exporter/pull/36
I know this looks like a total non-issue, but because I didn't expect two new plugins it took me about an hour to find the issue.

**Comment by akien-mga** [comment]
Fixed by #36.
