### ISSUE TITLE
Write an importer

### ISSUE THREAD

**Issue by ghost** [godotengine/collada-exporter#42]
Gaia Clary, the OpenCollada maintainer, suggested that a Python-based importer is developed [here](https://code.blender.org/2016/10/the-collada-case/#comment-75926).

This might be of little concern to Godot, of course, but now that BCE is its own thing and that a Blender dev implied that having an importer would improve the chance of BCE making it into Blender, I think it might be good to at least take into consideration the possibility and find out how many of us would be able to contribute to it.

I have no experience with the Blender API outside of my involvement with BCE but I have Python experience and can work with XML, so I would be willing to contribute. The problem is that I don't have much time to code, so unless someone else is willing to collaborate (especially on the Blender parts) I am afraid I won't be able to deliver soon enough.

Anybody willing to work on it?

**Comment by akien-mga** [comment]
As mentioned in #31, our focus in now glTF 2.0 so there won't be extensive dev work done on the COLLADA pipeline. It will stay supported for now, but the recommended format is glTF 2.0.
