### ISSUE TITLE
Use string formatting for XML output

### ISSUE THREAD

**Issue by paper-pauper** [godotengine/collada-exporter#5]
Currently the BCE uses raw string output to create XML elements:

``` Python
self.writel(S_FX, 3, '<newparam sid="' + surface_sid + '">')
```

This is both hard to read and hard to write. The Blender team suggests using string formatting like they did [here](https://developer.blender.org/diffusion/BA/browse/master/io_scene_x3d/export_x3d.py):

``` Python
fw('%s<Coordinate USE=%s />\n' % (indent, mesh_id_coords))
```

I suggest something entirely different and in my opinion easier to both read and write (since it takes care of indentation automatically, and is also less error-prone) - using `xml.etree.cElementTree` to generate the XML (which is fast enough) and then use `xml.dom.minidom` to prettify/indent it (both are included in the standard library).

**Comment by set-killer** [comment]
This is related to about 30-40% of the code. 

Which of the both methods is better to use? In my opinion using `xml.etree.cElementTree` would not make the code more easy to read and it will be harder to make the parenting of the XML nodes.
Anyone with experience on this?

(Just discussing the issue...)

**Comment by paper-pauper** [comment]
@set-killer I think that if unit tests for the XML generation are written, the `format` method can be just as reliable (and faster).

**Comment by paper-pauper** [comment]
I think it's best if at least for the time being, since it's what the Blender dev requested and it'd be great to have Blender devs working on this plugin as soon as possible, we go ahead with `format` for the XML output.

@set-killer If you can take this and push a commit in a reasonable time please tell me, otherwise I can do it myself in a few days (hopefully).

**Comment by set-killer** [comment]
Yes, working on it.
