### ISSUE TITLE
Clean comments and docstrings

### ISSUE THREAD

**Issue by paper-pauper** [godotengine/collada-exporter#8]
There are a lot of comments and docstrings which are either:
* Wondering if something works
* Redundant
* Commented out code

They are confusing and make the script look amateurish, so I think they should be removed.

**Comment by paper-pauper** [comment]
I suggest splitting this into two separate commits - first the comments, then the commented out code. This way, it will be easy to find all commented out code, in case it is ever needed.

**Comment by paper-pauper** [comment]
@set-killer It's only this and #10 before the plugin can be sent to the Blender devs. Do you want to split the load? #10 is easier (just delete a few lines) but requires a bit of testing (but I don't believe any of those unused variables are any useful), this one requires no testing but it's a bit more work. If so please tell me, so that we don't work on the same things (otherwise I'll work on both myself).

**Comment by paper-pauper** [comment]
I'm thinking about removing the superfluous comments (commenting one to five lines when what they do is pretty clear is not that useful), and posting the various doubts and hacks expressed by some comments on the issue tracker. I think I will go ahead and do it, please tell me if you have a problem with that.

**Comment by akien-mga** [comment]
Fine by me.

**Comment by set-killer** [comment]
@paper-pauper I wouldn't be able to take care for this in the next few hours. If you have this opportunity please do it. Also i'm not sure if we should leave some of the comments untouched or remove them all. I guess you have better overview in this issue, so please go ahead.

**Comment by set-killer** [comment]
oh, its actually done! Nice :tada:

**Comment by paper-pauper** [comment]
Only the commented out code is done, I'll do the comments myself tomorrow perhaps. Thanks for re-opening the ticket by the way, it's best to leave it open until the other part is done.

**Comment by set-killer** [comment]
w8, there is some minor thing here:
https://github.com/godotengine/collada-exporter/blob/master/io_scene_dae/__init__.py#L150

will try to fix it fast...

**Comment by set-killer** [comment]
Done.

@paper-pauper you did a great job. Nouce!
