### ISSUE TITLE
Blender 2.8 Layers and Collection support?

### ISSUE THREAD

**Issue by BlackScorp** [godotengine/collada-exporter#81]
Hello Guys,

in Blender 2.8 you can create collections in a Scene and i wonder if those will be supported in the collada exporter.

https://code.blender.org/2017/09/view-layers-and-collections/  as you can see here the Scene structure was changed.

I assume that nested Layers should fit perfectly in Godot.

Best regards

**Comment by Calinou** [comment]
See also #96.

**Comment by Calinou** [comment]
The add-on was updated for Blender 3.0 https://github.com/godotengine/collada-exporter/pull/131, but support for collections is still not implemented. However, given Collada is considered to be in maintenance mode compared to glTF 2.0, this may take a while to be implemented (if ever).

**Comment by BlackScorp** [comment]
@Calinou yeah glTF is what iam using, i close this issue
