### ISSUE TITLE
Using animations with hints will use the wrong track path.

### ISSUE THREAD

**Issue by spongeboburu** [godotengine/collada-exporter#89]
When animating objects using -rigid or -col* the object is renamed from "name-suffix" to just "name", yet the animation tracks still refers to "name-suffix".

Example: "Cube-rigid" becomes "Cube" in godot, but the transform track in the animation still refers to "Cube-rigid".

**Comment by Calinou** [comment]
https://github.com/godotengine/godot/issues/23302 was closed, so I'll assume this is fixed as well.
