### ISSUE TITLE
Format your floating-point data!

### ISSUE THREAD

**Issue by mick-p1982** [godotengine/collada-exporter#90]
Sorry, if you're going to claim to be "Better" you gotta change how you are outputting/formatting floating-point data. Something tells me there is no way the data round-trips, and it's so wasteful and full of extraneous/erroneous digits. Compare these two files, and guess which is yours:

[Better-COLLADA.zip](https://github.com/godotengine/collada-exporter/files/2521680/Better-COLLADA.zip)

**Comment by Calinou** [comment]
@mick-p1982 The add-on was updated to 3.0 by https://github.com/godotengine/collada-exporter/pull/131. If you're interested in improving the formatting of floating-point data, please open a pull request :slightly_smiling_face:

**Comment by Calinou** [comment]
Closing due to lack of response.
