### ISSUE TITLE
Vertices are duplicated when exported

### ISSUE THREAD

**Issue by hockdudu** [godotengine/collada-exporter#95]
The exported Collada file has duplicated vertices. Each face has its own vertices instead of sharing them. As a result from the vertices being separated, I cannot apply shaders on Godot correctly.

For example: On the Blender's startup file, there is a cube. When I export it, there are 24 vertices (or 36 if triangulate is ticked) on the exported model instead of 8.

On the file "Collada.zip" I have the default Blender cube exported with both Better Collada and the default Collada exporter. As it can be seen (i.e. by reimporting the files or analysing them manually), there are 36 vertices on BetterColladaTrianglesCube.dae, whereas there are only 8 vertices on BlenderColladaCube.dae.

[Collada.zip](https://github.com/godotengine/collada-exporter/files/2730482/Collada.zip)

The issue can be replicated by simply creating a new project/file on Blender and exporting the cube.

OS: Arch Linux
Blender version: 2.79
Better Collada version: Last version (9a8fae9)

**Comment by bojidar-bg** [comment]
This is likely related to flat shading. With flat shading, you usually duplicate vertices so that normals won't be interpolated (similar to what the Edge Split modifier does).

**Comment by gregeryb** [comment]
BetterCollada duplicates vertices if the mode is set to "flat" and merges vertices in "smooth" mode. The cube exports as 24 vertices and 24 normals in flat mode, in smooth mode it's 8 vertices and 8 normals. 

The vertex data doesn't need to be duplicated in flat mode, a flat cube can be done with 8 vertices and 6 normals. That can be done by having seperate normals and indexing a different normal for shared each face. 

As it works now there whouldn't be much difference in the gaming engine apart from taking up extra storage in the DAE file. Maybe explain what problem you're having with the shader.

**Comment by hockdudu** [comment]
Setting the shading mode to "smooth" solved the problem. Thank you very much!
