### ISSUE TITLE
Upgrade for Blender 2.8/2.9/3.0 or later

### ISSUE THREAD

**Issue by daniloulf** [godotengine/collada-exporter#96]
is planned a version for Blender 2.8 beta

**Comment by Zamundaaa** [comment]
I'm wondering this as well. Because One can't really use animations without a proper exporter...
And opening a 2.8 file in 2.7x doesn't work

**Comment by daniloulf** [comment]
Seems that the project is off. The dae-standart-exporter does not work well.

**Comment by JigmeDatse** [comment]
https://github.com/godotengine/godot-blender-exporter as mentioned by @daniloulf works.  It's doing a different thing, but in 2.91 it's showing up, and exporting a .escn file that I can drop into my Godot project.  

Unfortunately it looks like little is getting done with this project (Better Godot Exporter) besides people putting issues on it.  At least if I'm reading the information on the code page correctly.

**Comment by Calinou** [comment]
> Unfortunately it looks like little is getting done with this project (Better Godot Exporter) besides people putting issues on it. At least if I'm reading the information on the code page correctly.

This is why I opened https://github.com/godotengine/godot-proposals/issues/2130 :slightly_smiling_face:

**Comment by Calinou** [comment]
Fixed by https://github.com/godotengine/collada-exporter/pull/131. Please open separate issues for any bugs you might encounter.
