### ISSUE TITLE
Exported Albedo Colors Are Different

### ISSUE THREAD

**Issue by NoodleSushi** [godotengine/collada-exporter#97]
![capture](https://user-images.githubusercontent.com/34954180/51746514-5eb28900-20e1-11e9-8236-fcca3cdb7d9b.PNG)
![capture](https://user-images.githubusercontent.com/34954180/51746661-dda7c180-20e1-11e9-8de4-5711039d010b.PNG)
Top Scene is from "Better" Collada exporter
Bottom Scene is The Original

2nd pic is the screen capture from blender

Original Table Top Color is #C4694D
while the Exported Color is #8C2413

**Comment by pouleyKetchoupp** [comment]
You can solve this issue by using the fix from PR #33 and uncheck "Apply Gamma Correction" in the export options.
